Abstract the database
Keep-Reth-Strange/reth-crawler pull request #20
Opened 2023-10-24 13:59 UTC by alessandromazza98

Should close #13 
This is just the draft so that you can check

2023-10-26 10:24 UTC, 0xprames commented
lmk when you've rebased against master and i'll take a closer look

2023-10-26 13:14 UTC, alessandromazza98 commented
Just to add some notes. What I plan immediately after merging this PR is:
- delete the `--save-to-json` flag that is now completely useless.
- delete also the `InMemoryDb` done using `HashMap`. We can replace it using an in memory db through SQLite or simply not adding it since the SQLite is already serverless and does not require any configuration to be run.
- update `README`.

2023-10-29 14:06 UTC, 0xprames commented
can we split this up into

- SQLite db
- bringing the APIserver in (this is higher priority rn)

as well as a rebase?

2023-10-29 14:10 UTC, 0xprames commented
i can take up the apiserver refactor - after we get that in, we can take a look at getting this sqlite PR in

2023-10-30 07:27 UTC, 0xprames approved these changes

2023-10-30 07:27 UTC, 0xprames commented on bins/reth-crawler/src/api_server/peerdb/app_state.rs
> +    store: Arc<dyn PeerDB>,
should be possible to make `AppState` here (and the rest of the references) generic over the PeerDB trait

2023-10-30 07:29 UTC, 0xprames commented
i think overall this looks OK - im indexing a bit more on getting this in to unblock #28 more than anything else rn.

i would rather us use generics over the `dyn PeerDB` - but we can tackle that as a follow up

2023-10-30 07:30 UTC, 0xprames commented on bins/reth-crawler/src/api_server/mod.rs
> +pub async fn start_api_server(sql_db: bool) -> Result<(), Box<dyn std::error::Error>> {
longer term - apiserver always starts with sqldb imo

2023-10-30 07:32 UTC, 0xprames commented on bins/reth-crawler/src/crawler/factory.rs
> +    pub async fn make(&self, sql_db: bool) -> CrawlerService {
eventually would be nice to remove the use of bool flags like this (`sql_db` works for now but in the future if there are more than 2 possibilities?)

probably makes sense to use an enum - and even then it'd be nice to see if there's a better way to do this (without passing in this flag at all, maybe creating the DB separately and passing it as a generic param to make?)

2023-10-30 07:47 UTC, 0xprames requested changes
should be ready for merge this after splitting up the DB part from apiserver part and only including the DB related changes

2023-10-30 17:04 UTC, closed without merging